name: front
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  mqtt5_client: ^3.4.0
  typed_data: '^1.3.1'
  event_bus: '^2.0.0'
  # path: '^1.8.2'
  # crypto: '^3.0.2'
  meta: '^1.8.0'
  mqtt_client: ^9.8.1
  ini: '>=1.0.0'
  # test: '>=0.12.0'
  crypto: ^3.0.3
  convert: ^3.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
